version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '8080:80'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - ./backend:/app # Map your backend folder to the container
      - /home/niky/vscodePC/juliakocevas/gcp-key.json:/app/gcp-key.json # Mount the keyfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
