apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: juliakocevas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: eclair2093/juliakocevas-backend-local:latest
          ports:
            - containerPort: 5000
