apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: juliakocevas
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
