apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: juliakocevas
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001 # Expose the backend service on port 30001
