apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: juliakocevas
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80 # Frontend apps typically serve on port 80
      targetPort: 8080
      nodePort: 30002 # Expose frontend on port 30002
